### ISSUE TITLE
Raises error when upgrading gir1.2-gexiv2 library to 0.10.4.1

### ISSUE THREAD

**Issue by pablo33** [pablo33/PHWorkflow#11]
Upgrading gir1.2-gexiv2 library to 0.10.4.1~jensge1\~yakkety3  raises an error. Could not use GExiv2.Metadata ('path to file')  in order to retrieve image's metadata.  Something has changed.

Workaround: force gir1.2-gexiv2 to version 0.10.3-2 (yakkety)

**Comment by pablo33** [comment]
Error raised:

=====
```
Traceback (most recent call last):
  File "PhotodeliverII.py", line 1002, in <module>
    Totalfiles += mediascan (destlocation)
  File "PhotodeliverII.py", line 510, in mediascan
    mediaadd (a)  # Add item's info to DB
  File "PhotodeliverII.py", line 483, in mediaadd
    filename, fileext, filebytes, Imdatestart, fnDateTimeOriginal, MetaDateTimeOriginal, Statdate, TimeOriginal, decideflag, imserie, imserial = mediainfo (abspath, forceassignfromfilename)
  File "PhotodeliverII.py", line 433, in mediainfo
    ImageMake, ImageModel, textdate = Fetchmetadata (abspath)
  File "PhotodeliverII.py", line 287, in Fetchmetadata
    metadata = GExiv2.Metadata(imagepath)
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
```
==================

Updated to Ubuntu 17.04, >>  set gir1.2-gexiv2-0.10 package locked at  version  0.10.4-2

**Comment by pablo33** [comment]
Updated the system: these packages are stable within the software:

```
gir1.2-gexiv2-0.10    (Version: 0.10.6-0~jensge0~zesty2)
python3-gexiv2         (Version:  0.10.6-0~jensge0~zesty2)
```
