### ISSUE TITLE
No png convert

### ISSUE THREAD

**Issue by pablo33** [pablo33/PHWorkflow#13]
Png convert doesn't work.

```
Processing files at/home/pablo/Dropbox/Camerainbox/
1 files where fetched at /home/pablo/Dropbox/Camerainbox/
Traceback (most recent call last):
  File "PhotodeliverII.py", line 1030, in <module>
    Totalfiles += mediascan (destlocation)
  File "PhotodeliverII.py", line 511, in mediascan
    mediaadd (a)  # Add item's info to DB
  File "PhotodeliverII.py", line 483, in mediaadd
    filename, fileext, filebytes, Imdatestart, fnDateTimeOriginal, MetaDateTimeOriginal, Statdate, TimeOriginal, decideflag, imserie, imserial = mediainfo (abspath, forceassignfromfilename)
  File "PhotodeliverII.py", line 433, in mediainfo
    ImageMake, ImageModel, textdate = Fetchmetadata (abspath)
  File "PhotodeliverII.py", line 287, in Fetchmetadata
    metadata = GExiv2.Metadata(imagepath)
  File "/usr/lib/python3/dist-packages/gi/overrides/GExiv2.py", line 41, in __init__
    self.open_path(path)
  File "/usr/lib/python3/dist-packages/gi/overrides/GExiv2.py", line 45, in open_path
    super(Metadata, self).open_path(path)
GLib.Error: GExiv2: unsupported format (501)
```

**Comment by pablo33** [comment]
PNG images has a transparent layer, it has an RGBA space for the color. Just plained de image to RGB space before converting to jpg format.

Added MTS as video file.
python Image objects are closed now.
