### ISSUE TITLE
Crash with this filename

### ISSUE THREAD

**Issue by pablo33** [pablo33/PHWorkflow#15]
IMG-20190704-16-34WA0006.jpg

==================================================
Processing files at/home/pablo/Dropbox/Camerainbox/
Traceback (most recent call last):
  File "./commands/PhotodeliverII.py", line 1027, in <module>
    Totalfiles += mediascan (originlocation)
  File "./commands/PhotodeliverII.py", line 511, in mediascan
    mediaadd (a)  # Add item's info to DB
  File "./commands/PhotodeliverII.py", line 483, in mediaadd
    filename, fileext, filebytes, Imdatestart, fnDateTimeOriginal, MetaDateTimeOriginal, Statdate, TimeOriginal, decideflag, imserie, imserial = mediainfo (abspath, forceassignfromfilename)
  File "./commands/PhotodeliverII.py", line 422, in mediainfo
    fnDateTimeOriginal = datetime.datetime.strptime (textdate, '%Y:%m:%d %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2019:00:07 04:16:34' does not match format '%Y:%m:%d %H:%M:%S'

**Comment by pablo33** [comment]
Solved, now scans the whole string from right to left, assuming the right year is mostly on the left of the string.
